import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import {
  Fira_Code as FiraCode,
  Plus_Jakarta_Sans as PlusJakartaSans,
} from 'next/font/google';
import localFont from 'next/font/local';
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";

const fontCal = localFont({
  src: '../assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-cal',
});

const fontSans = PlusJakartaSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const fontMono = FiraCode({
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={cn(fontSans.variable, fontMono.variable, fontCal.variable)}
      suppressHydrationWarning>
         <div id="__app" className={cn('flex min-h-screen flex-col')}>
        <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
